import './components/header-height.js';
import './components/back-to-top.js';
import './components/banner.js';
import './components/burger.js';
import './components/swiper-quotes.js';
import './components/swiper-actors.js';
import './components/tab.js';
import './components/about-animation.js';
import './components/player.js';
